sudo: required
dist: trusty
language: node_js

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION="1.18.0"

node_js:
  - 'node'

before_install:
  # Install Node.js
  - nvm install 8
  - nvm use 8
  - node --version

  # Add token for @dashevo private npm registry
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

  # Add credential helper
  - git clone https://github.com/awslabs/amazon-ecr-credential-helper.git
  - cd amazon-ecr-credential-helper
  - make docker
  - sudo mv ./bin/local/docker-credential-ecr-login /usr/local/bin
  - cd ..
  - sudo rm -rf amazon-ecr-credential-helper
  - mkdir -p ~/.docker
  - "echo '{ \"credsStore\": \"ecr-login\" }' > ~/.docker/config.json"
  # Fix awslabs/amazon-ecr-credential-helper#9
  - echo '103738324493.dkr.ecr.us-west-2.amazonaws.com' | docker-credential-ecr-login get

install:
  - npm install

script:
  - npm run lint
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script: npm publish
  on:
    tags: true
    repo: dashevo/js-dp-services-ctl
