sudo: required
dist: trusty
language: node_js

node_js:
  - '8'
  - '10'

branches:
  only:
    - master
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)$/
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION="1.18.0"

before_install:
  # Add token for @dashevo private npm registry
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

  # Add credential helper
  - git clone https://github.com/awslabs/amazon-ecr-credential-helper.git
  - cd amazon-ecr-credential-helper
  - make docker
  - sudo mv ./bin/local/docker-credential-ecr-login /usr/local/bin
  - cd ..
  - sudo rm -rf amazon-ecr-credential-helper
  - mkdir -p ~/.docker
  - "echo '{ \"credsStore\": \"ecr-login\" }' > ~/.docker/config.json"
  # Fix awslabs/amazon-ecr-credential-helper#9
  - echo "$REPO_URL" | docker-credential-ecr-login get

install:
  - npm install

script:
  - npm run lint
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/travis-deploy.sh
  on:
    tags: true
    repo: dashevo/js-dp-services-ctl
